In [6]:
import regex as re
import nltk
import seaborn as sns
import numpy as np
from sklearn.metrics import mean_squared_error as MSE, r2_score
from scipy.stats import skew,kurtosis,zscore
from sklearn.metrics import accuracy_score
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [37]:
!unzip "/content/Restraunt_MH.zip"

Archive:  /content/Restraunt_MH.zip
replace Participants_Data_Final/Data_Train.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: Participants_Data_Final/Data_Train.xlsx  
replace __MACOSX/Participants_Data_Final/._Data_Train.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: __MACOSX/Participants_Data_Final/._Data_Train.xlsx  
replace Participants_Data_Final/Data_Test.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: Participants_Data_Final/Data_Test.xlsx  
replace __MACOSX/Participants_Data_Final/._Data_Test.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: __MACOSX/Participants_Data_Final/._Data_Test.xlsx  
replace Participants_Data_Final/Sample_submission.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: Participants_Data_Final/Sample_submission.xlsx  
replace __MACOSX/Participants_Data_Final/._Sample_submission.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: __MACOSX/Participants_Data_Final/._Sample_submission.xlsx  


# Prediction

In [293]:
df = pd.read_excel("/content/Participants_Data_Final/Data_Train.xlsx")

In [294]:
df.head(2)

TITLE  RESTAURANT_ID  ...     VOTES  COST
0      CASUAL DINING           9438  ...  49 votes  1200
1  CASUAL DINING,BAR          13198  ...  30 votes  1500

[2 rows x 9 columns]

In [295]:
df['COST'].skew()

3.9788007578247573

In [296]:
df = df.drop(['RESTAURANT_ID'],1)

In [297]:
y = df.COST

In [298]:
df.isnull().values.any()

True

In [299]:
df.isnull().sum()

TITLE          0
CUISINES       0
TIME           0
CITY         112
LOCALITY      98
RATING         2
VOTES       1204
COST           0
dtype: int64

In [300]:
df['CITY'].fillna('missingcity', inplace=True)
df['LOCALITY'].fillna('missinglocality', inplace=True)
df['VOTES'].fillna('0 votes', inplace=True)
df = df.fillna(0)

In [301]:
df.isnull().sum()

TITLE       0
CUISINES    0
TIME        0
CITY        0
LOCALITY    0
RATING      0
VOTES       0
COST        0
dtype: int64

In [302]:
df['VOTES'] = df['VOTES'].apply(lambda x: x.split('votes')[0])

In [303]:
df['RATING'] = df['RATING'].replace('-', '0')
df['RATING'] = df['RATING'].replace('NEW', '0')

In [304]:
df_num = df[['VOTES','RATING']]
df_num.head(2)

VOTES RATING
0   49     3.6
1   30     4.2

In [305]:
print(*df_num['RATING'])

3.6 4.2 3.8 4.1 3.8 4.0 4.1 4.3 3.9 3.3 4.1 4.0 3.4 0 4.0 4.5 3.6 3.5 3.6 4.1 4.2 4.0 4.0 3.9 4.2 3.8 3.4 4.1 4.3 4.2 3.5 4.0 4.0 4.4 2.7 3.3 3.7 4.3 4.0 3.4 3.3 3.8 3.3 4.0 4.2 4.1 4.0 3.9 4.7 4.3 3.3 4.0 3.9 3.7 3.7 3.8 3.3 3.6 4.0 3.9 3.6 3.6 0 4.0 3.7 4.3 3.4 4.3 3.3 0 4.0 3.6 4.3 4.0 4.3 3.5 3.1 3.4 3.9 3.8 4.0 3.8 4.0 4.2 4.0 0 3.8 3.1 3.7 4.1 4.1 4.0 3.9 3.4 3.9 4.2 3.8 3.9 3.8 3.7 3.8 3.4 3.5 4.0 2.7 4.3 4.2 3.4 4.0 4.1 3.7 0 3.7 3.6 4.1 4.0 3.4 0 4.4 3.8 0 3.6 3.6 4.2 3.3 4.3 3.1 3.9 3.7 3.6 4.2 3.9 4.0 3.8 3.9 3.5 3.9 4.1 3.8 3.8 3.5 3.8 3.7 4.0 3.9 4.7 3.7 4.2 4.0 3.5 4.2 3.3 3.8 4.0 3.7 4.0 0 3.7 4.2 2.5 3.8 3.7 3.4 3.9 3.5 0 3.7 4.1 4.1 3.1 4.3 3.9 4.0 3.4 4.2 3.8 4.1 4.3 0 4.5 3.5 3.1 3.5 4.0 4.1 3.1 4.6 4.1 3.9 2.8 3.9 3.5 3.9 4.3 0 4.3 4.6 3.8 3.7 4.0 3.6 3.8 4.1 3.7 0 3.6 4.7 4.7 3.9 4.1 3.9 3.8 0 4.1 0 0 3.7 3.8 3.8 4.0 3.6 3.5 3.5 3.9 3.7 3.8 3.7 0 3.6 3.3 4.0 4.2 3.0 3.6 3.8 0 4.0 4.0 4.0 2.8 3.6 3.6 2.7 4.0 3.9 4.1 3.4 3.8 3.3 3.7 3.4 3.6 3.8 0 3.7 4.3 3.2 3.8 3.9 

In [306]:
df_txt = df.drop(['VOTES','RATING'],1)
df_txt.head(2)

TITLE                        CUISINES  ...        LOCALITY  COST
0      CASUAL DINING     Malwani, Goan, North Indian  ...  Dombivali East  1200
1  CASUAL DINING,BAR  Asian, Modern Indian, Japanese  ...       Ramapuram  1500

[2 rows x 6 columns]

In [307]:
df_txt['main'] = df_txt[df_txt.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1)

df_txt.main.head(3)

0    CASUAL DINING,Malwani, Goan, North Indian,11am...
1    CASUAL DINING,BAR,Asian, Modern Indian, Japane...
2    CASUAL DINING,North Indian, Chinese, Biryani, ...
Name: main, dtype: object

In [308]:
X_text = df_txt.main

In [309]:
import regex as re
model = []
for i in range(0, df.shape[0]):
    data = re.sub(r'\W', ' ', str(X_text[i]))
    data = data.lower()
    data = re.sub(r'\s+[a-z]\s+', ' ',data)
    data = re.sub(r'\s+', ' ', data)
    model.append(data)   

In [310]:
model[0]

'casual dining malwani goan north indian 11am 4pm 7 30pm 11 30pm mon sun thane dombivali east 1200'

In [311]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [312]:
vector = TfidfVectorizer(max_features = 2000, min_df = 1, max_df = 0.99, stop_words = stopwords.words('english'))
X_text = vector.fit_transform(model).toarray()

In [313]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [314]:
df_num = scaler.fit_transform(df_num,1)
df_num

array([[1.18972466e-03, 7.34693878e-01],
       [7.28402855e-04, 8.57142857e-01],
       [5.36590103e-03, 7.75510204e-01],
       ...,
       [1.47622979e-02, 8.16326531e-01],
       [7.76963046e-04, 7.14285714e-01],
       [1.64376244e-02, 6.93877551e-01]])

In [315]:
X_num = df_num

In [316]:
X = np.concatenate((X_text,X_num),axis = 1)
X

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.18972466e-03, 7.34693878e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 7.28402855e-04, 8.57142857e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 5.36590103e-03, 7.75510204e-01],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.47622979e-02, 8.16326531e-01],
       [0.00000000e+00, 0.00000000e+00, 2.26034763e-01, ...,
        0.00000000e+00, 7.76963046e-04, 7.14285714e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.64376244e-02, 6.93877551e-01]])

# Fitting

In [317]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state = 42)

In [318]:
from sklearn.ensemble import RandomForestRegressor

In [319]:
regr = RandomForestRegressor(n_jobs = -1, random_state = 42, n_estimators = 100, verbose = 2)

In [320]:
regr.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.


building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100


[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:  1.1min


building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80

[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  2.9min finished


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=42, verbose=2, warm_start=False)

In [321]:
import numpy as np

pred1 = regr.predict(X_test)
pred2 = regr.predict(X_train) 
rmse = np.sqrt(MSE(y_test, pred1)) 
print("RMSE : % f" %(rmse)) 

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  37 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  37 tasks      | elapsed:    0.1s


RMSE :  98.302448


[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.3s finished


In [322]:
print(r2_score(y_test,pred1)*100)
print(r2_score(y_train,pred2)*100)

97.35512309319328
98.46302471805905


In [348]:
import lightgbm as lgb
train = lgb.Dataset(X_train, label=y_train)
test = lgb.Dataset(X_test, label=y_test)

In [387]:
param = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': ['l2', 'auc'],
   'num_iterations':80,
         'learning_rate': 0.1,  
         'num_leaves': 65,
         'max_depth': 60, 
         'min_data_in_leaf': 1, 
         'max_bin': 35, 
         'min_data_in_bin':10, 
         'random_state' : 42 
}

In [388]:
gbm = lgb.LGBMRegressor(**param)

In [389]:
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='l1',
        early_stopping_rounds = 100)

/usr/local/lib/python3.6/dist-packages/lightgbm/engine.py:118: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


[1]	valid_0's l2: 304077	valid_0's auc: 1	valid_0's l1: 370.175
Training until validation scores don't improve for 100 rounds.
[2]	valid_0's l2: 254412	valid_0's auc: 1	valid_0's l1: 338.7
[3]	valid_0's l2: 214897	valid_0's auc: 1	valid_0's l1: 312.596
[4]	valid_0's l2: 182091	valid_0's auc: 1	valid_0's l1: 287.533
[5]	valid_0's l2: 155464	valid_0's auc: 1	valid_0's l1: 265.312
[6]	valid_0's l2: 134008	valid_0's auc: 1	valid_0's l1: 245.765
[7]	valid_0's l2: 114155	valid_0's auc: 1	valid_0's l1: 227.014
[8]	valid_0's l2: 98563.3	valid_0's auc: 1	valid_0's l1: 210.406
[9]	valid_0's l2: 85486.3	valid_0's auc: 1	valid_0's l1: 195.396
[10]	valid_0's l2: 74929.8	valid_0's auc: 1	valid_0's l1: 181.354
[11]	valid_0's l2: 65047.1	valid_0's auc: 1	valid_0's l1: 168.662
[12]	valid_0's l2: 56023.1	valid_0's auc: 1	valid_0's l1: 156.519
[13]	valid_0's l2: 49191.8	valid_0's auc: 1	valid_0's l1: 146.047
[14]	valid_0's l2: 44067.6	valid_0's auc: 1	valid_0's l1: 137.242
[15]	valid_0's l2: 38934.4	vali

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_bin=35,
              max_depth=60, metric=['l2', 'auc'], min_child_samples=20,
              min_child_weight=0.001, min_data_in_bin=10, min_data_in_leaf=1,
              min_split_gain=0.0, n_estimators=100, n_jobs=-1,
              num_iterations=80, num_leaves=65, objective='regression',
              random_state=42, reg_alpha=0.0, reg_lambda=0.0, silent=True,
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0,
              task='train')

In [390]:
pred01 = gbm.predict(X_test, num_iteration=gbm.best_iteration_) 
rmse = np.sqrt(MSE(y_test, pred01)) 
print("RMSE : % f" %(rmse)) 

RMSE :  82.741489


In [391]:
r2_score(y_test,pred01)*100

98.12619901025954

# Test Set

In [392]:
df = pd.read_excel("/content/Participants_Data_Final/Data_Test.xlsx")

In [393]:
df.head(2)

TITLE  RESTAURANT_ID  ... RATING      VOTES
0  CASUAL DINING           4085  ...    4.3  564 votes
1    QUICK BITES          12680  ...    4.2   61 votes

[2 rows x 8 columns]

In [394]:
df = df.drop(['RESTAURANT_ID'],1)

In [395]:
df.isnull().values.any()

True

In [396]:
df.isnull().sum()

TITLE         0
CUISINES      0
TIME          0
CITY         35
LOCALITY     30
RATING        2
VOTES       402
dtype: int64

In [397]:
df['CITY'].fillna('missingcity', inplace=True)
df['LOCALITY'].fillna('missinglocality', inplace=True)
df['VOTES'].fillna('0 votes', inplace=True)
df = df.fillna(0)

In [398]:
df.isnull().sum()

TITLE       0
CUISINES    0
TIME        0
CITY        0
LOCALITY    0
RATING      0
VOTES       0
dtype: int64

In [399]:
df['VOTES'] = df['VOTES'].apply(lambda x: x.split('votes')[0])

In [400]:
df['RATING'] = df['RATING'].replace('-', '0')
df['RATING'] = df['RATING'].replace('NEW', '0')

In [401]:
df_num = df[['VOTES','RATING']]
df_num.head(2)

VOTES RATING
0  564     4.3
1   61     4.2

In [402]:
df_txt = df.drop(['VOTES','RATING'],1)
df_txt.head(2)

TITLE  ...    LOCALITY
0  CASUAL DINING  ...   Sector 18
1    QUICK BITES  ...  Grant Road

[2 rows x 5 columns]

In [403]:
df_txt['main'] = df_txt[df_txt.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1)

df_txt.main.head(3)

0    CASUAL DINING,North Indian, Chinese, Mughlai, ...
1    QUICK BITES,South Indian, Fast Food, Pizza, No...
2    CASUAL DINING,North Indian, Seafood, Biryani, ...
Name: main, dtype: object

In [404]:
X_text = df_txt.main

In [405]:
import regex as re
model = []
for i in range(0, df.shape[0]):
    data = re.sub(r'\W', ' ', str(X_text[i]))
    data = data.lower()
    data = re.sub(r'\s+[a-z]\s+', ' ',data)
    data = re.sub(r'\s+', ' ', data)
    model.append(data)   

In [406]:
model[0]

'casual dining north indian chinese mughlai kebab 12noon 12midnight mon sun noida sector 18'

In [407]:
#vector = TfidfVectorizer(max_features = 4000, min_df = 1, max_df = 0.8, stop_words = stopwords.words('english'))
X_text = vector.transform(model).toarray()

In [408]:
X_num = scaler.transform(df_num)
X_num

array([[0.01369397, 0.87755102],
       [0.00148109, 0.85714286],
       [0.00849803, 0.7755102 ],
       ...,
       [0.00128685, 0.75510204],
       [0.        , 0.        ],
       [0.00152965, 0.75510204]])

In [409]:
X = np.concatenate((X_text,X_num),axis = 1)
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.01369397,
        0.87755102],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00148109,
        0.85714286],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00849803,
        0.7755102 ],
       ...,
       [0.        , 0.        , 0.22856814, ..., 0.        , 0.00128685,
        0.75510204],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00152965,
        0.75510204]])

In [410]:
predictions = gbm.predict(X)

In [411]:
predictions

array([860.45142493, 529.73684599, 745.89159924, ..., 543.91516285,
       540.60416542, 564.00737391])

In [412]:
df_sub = pd.DataFrame(data = predictions, columns=['COST'])

In [413]:
df_sub.to_csv('result_res.csv',index =False)