In [ ]:
#!unzip "exam_mark_prediction_ai_challenge-dataset.zip"

In [ ]:
!wget -O "exam_mark_prediction_ai_challenge-dataset.zip" "https://dockship-job-models.s3.ap-south-1.amazonaws.com/621e9e5be5f5ea8483af8a3729779cb8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIDOPTEUZ2LEOQEGQ%2F20210228%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210228T074906Z&X-Amz-Expires=1800&X-Amz-Signature=0db789a8ddb785b844d63431ddf24aa258e77dfff18f594cf3bc058e1239b409&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22exam_mark_prediction_ai_challenge-dataset.zip%22"

--2021-02-28 07:53:18--  https://dockship-job-models.s3.ap-south-1.amazonaws.com/621e9e5be5f5ea8483af8a3729779cb8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIDOPTEUZ2LEOQEGQ%2F20210228%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210228T074906Z&X-Amz-Expires=1800&X-Amz-Signature=0db789a8ddb785b844d63431ddf24aa258e77dfff18f594cf3bc058e1239b409&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22exam_mark_prediction_ai_challenge-dataset.zip%22
Resolving dockship-job-models.s3.ap-south-1.amazonaws.com (dockship-job-models.s3.ap-south-1.amazonaws.com)... 52.219.64.127
Connecting to dockship-job-models.s3.ap-south-1.amazonaws.com (dockship-job-models.s3.ap-south-1.amazonaws.com)|52.219.64.127|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11711 (11K) [binary/octet-stream]
Saving to: ‘exam_mark_prediction_ai_challenge-dataset.zip’

exam_mark_predictio 100%[===================>]  11.44K  --.-KB/s    in 0s      

2021-02-28

In [ ]:
import regex as re
import nltk
import seaborn as sns
from scipy.sparse import hstack, csr_matrix
import numpy as np
from sklearn.metrics import mean_squared_error as MSE, r2_score
from scipy.stats import skew,kurtosis,zscore
from sklearn.metrics import accuracy_score
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Model

In [ ]:
df = pd.read_csv("/content/exam_mark_prediction_ai_challenge-dataset/train.csv")

In [ ]:
df.describe()

Unnamed: 0  reading score  writing score  math score
count   700.00000     700.000000     700.000000  700.000000
mean    349.50000      69.751429      68.497143   66.442857
std     202.21688      14.600877      15.224265   15.249227
min       0.00000      23.000000      15.000000    8.000000
25%     174.75000      60.000000      58.000000   57.000000
50%     349.50000      70.000000      70.000000   66.500000
75%     524.25000      80.000000      79.000000   77.000000
max     699.00000     100.000000     100.000000  100.000000

In [ ]:
df.shape

(700, 9)

In [ ]:
df = df.drop(['Unnamed: 0'],1)
df.head(2)

gender ethnicity  ... writing score math score
0    male   group C  ...            62         61
1  female   group C  ...            53         53

[2 rows x 8 columns]

In [ ]:
med_price_per_mat_dict = df.groupby('ethnicity')['writing score'].mean().to_dict()

In [ ]:
df['med_price_per_mat'] = df['ethnicity'].map(med_price_per_mat_dict )

In [ ]:
df['ethnicity'].value_counts()

group C    219
group D    184
group B    141
group E     98
group A     58
Name: ethnicity, dtype: int64

In [ ]:
df_text = df[['ethnicity','gender','parental level of education','lunch','test preparation course']]

In [ ]:
df_num = df[['reading score','writing score']]

In [ ]:
y = df['math score']

In [ ]:
df_num.skew()

reading score   -0.228772
writing score   -0.252597
dtype: float64

In [ ]:
df_text['main'] = df_text[df_text.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1)

df_text.main.head(3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


0              group C,male,some college,standard,none
1      group C,female,associate's degree,standard,none
2    group C,female,some college,free/reduced,compl...
Name: main, dtype: object

In [ ]:
X_text = df_text.main

In [ ]:
import regex as re
model = []
for i in range(0, df.shape[0]):
    data = re.sub(r'\W', ' ', str(X_text[i]))
    data = data.lower()
    data = re.sub(r'^br$', ' ', data)
    data = re.sub(r'\s+br\s+',' ',data)
    data = re.sub(r'\s+[a-z]\s+', ' ',data)
    data = re.sub(r'^b\s+', '', data)
    data = re.sub(r'\s+', ' ', data)
    model.append(data)   

In [ ]:
model[0]

'group male some college standard none'

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
vector = TfidfVectorizer(max_features = 10, min_df = 1, max_df = 0.99, stop_words = stopwords.words('english'))
#vector = CountVectorizer(stop_words=None)
X_text = vector.fit_transform(model).toarray()

In [ ]:
X_text.shape

(700, 10)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [ ]:
df_num.shape

(700, 2)

In [ ]:
df_num = scaler.fit_transform(df_num,1)
df_num

array([[0.49350649, 0.55294118],
       [0.50649351, 0.44705882],
       [0.67532468, 0.64705882],
       ...,
       [0.48051948, 0.56470588],
       [0.7012987 , 0.69411765],
       [0.64935065, 0.62352941]])

In [ ]:
X_num = df_num

In [ ]:
X = np.concatenate((X_text,X_num),axis = 1)
X

array([[0.        , 0.        , 0.        , ..., 0.53665809, 0.49350649,
        0.55294118],
       [0.        , 0.60496409, 0.50234358, ..., 0.4375157 , 0.50649351,
        0.44705882],
       [0.52509162, 0.        , 0.4209501 , ..., 0.        , 0.67532468,
        0.64705882],
       ...,
       [0.51953421, 0.        , 0.        , ..., 0.        , 0.48051948,
        0.56470588],
       [0.        , 0.60496409, 0.50234358, ..., 0.4375157 , 0.7012987 ,
        0.69411765],
       [0.        , 0.48011869, 0.3986758 , ..., 0.        , 0.64935065,
        0.62352941]])

In [ ]:
X1 = pd.DataFrame(X)
X1
X = X1.copy()

# Pred

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [ ]:
reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
predl = reg.predict(X_test) 
predl1 = reg.predict(X_train) 
rmse = np.sqrt(MSE(y_test, predl)) 
print(np.sqrt(MSE(y_train, predl1))) 
print("RMSE : % f" %(rmse)) 

5.560740067938667
RMSE :  6.711644


In [ ]:
predl

array([80.93158295, 62.90033295, 45.55658295, 71.22845795, 70.11908295,
       61.13470795, 66.41595795, 74.65815739, 61.93158295, 63.49557167,
       48.61908295, 40.32540703, 53.09423112, 55.49408295, 62.18158295,
       84.43158295, 60.18158295, 68.52533295, 57.24408295, 41.99408295,
       79.49408295, 41.61908295, 61.58783295, 78.80658295, 54.33783295,
       58.86908295, 37.88470795, 53.55658295, 62.49408295, 66.22845795,
       64.86908295, 88.43158295, 74.40033295, 75.25511333, 61.93158295,
       99.08783295, 64.01118555, 93.40033295, 70.24408295, 54.13470795,
       48.8614501 , 49.27533295, 67.87680473, 46.64257946, 78.65033295,
       72.33783295, 54.55658295, 80.99408295, 79.10345795, 90.99408295,
       80.81582941, 73.24408295, 54.18158295, 68.94423641, 71.64434541,
       69.72845795, 66.30658295, 61.02525678, 75.72845795, 64.80658295,
       72.40033295, 99.99408295, 75.44720795, 83.36908295, 65.22845795,
       61.24408295, 76.49408295, 71.11908295, 66.45596938, 47.91

In [ ]:
print(r2_score(y_test,predl)*100)
print(r2_score(y_train,predl1)*100) #75.35386497980654 #6.577887

74.83709678340156
87.00871112471918


In [ ]:
import lightgbm as lgb
train = lgb.Dataset(X_train, label=y_train)
test = lgb.Dataset(X_test, label=y_test)

In [ ]:
param = {'objective': 'regression',
         'boosting': 'gbdt', 
         'max_depth':10, 
         'metric': 'l2_root',
         'learning_rate': 0.1, 
         'num_iterations': 10000,
         'min_data_in_leaf': 15,
         'bagging_fraction': 0.90,
         'bagging_freq': 2,
         'bagging_seed': 3,
         'feature_fraction': 0.99,
         'feature_fraction_seed': 2,
         'early_stopping_round': 2000,
         'max_bin': 500
         }

In [ ]:
gbm = lgb.LGBMRegressor(**param)

In [ ]:
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='l1',
        early_stopping_rounds = 100)

[1]	valid_0's l1: 9.70355	valid_0's rmse: 12.3224
Training until validation scores don't improve for 2000 rounds.
[2]	valid_0's l1: 9.01486	valid_0's rmse: 11.4419
[3]	valid_0's l1: 8.38917	valid_0's rmse: 10.6866
[4]	valid_0's l1: 7.83506	valid_0's rmse: 9.98928
[5]	valid_0's l1: 7.34343	valid_0's rmse: 9.38712
[6]	valid_0's l1: 6.86163	valid_0's rmse: 8.83002
[7]	valid_0's l1: 6.52095	valid_0's rmse: 8.39579
[8]	valid_0's l1: 6.17362	valid_0's rmse: 8.00321
[9]	valid_0's l1: 5.94241	valid_0's rmse: 7.71616
[10]	valid_0's l1: 5.73557	valid_0's rmse: 7.49712
[11]	valid_0's l1: 5.53286	valid_0's rmse: 7.27286
[12]	valid_0's l1: 5.37127	valid_0's rmse: 7.11272
[13]	valid_0's l1: 5.24673	valid_0's rmse: 6.99207
[14]	valid_0's l1: 5.14701	valid_0's rmse: 6.89343
[15]	valid_0's l1: 5.09882	valid_0's rmse: 6.84896
[16]	valid_0's l1: 5.07256	valid_0's rmse: 6.81391
[17]	valid_0's l1: 5.02823	valid_0's rmse: 6.75276
[18]	valid_0's l1: 5.00903	valid_0's rmse: 6.71927
[19]	valid_0's l1: 5.02823	

/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:118: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:123: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))



[267]	valid_0's l1: 5.77765	valid_0's rmse: 7.27492
[268]	valid_0's l1: 5.77778	valid_0's rmse: 7.2758
[269]	valid_0's l1: 5.77856	valid_0's rmse: 7.27678
[270]	valid_0's l1: 5.78005	valid_0's rmse: 7.27511
[271]	valid_0's l1: 5.78378	valid_0's rmse: 7.27738
[272]	valid_0's l1: 5.77498	valid_0's rmse: 7.26664
[273]	valid_0's l1: 5.76843	valid_0's rmse: 7.25783
[274]	valid_0's l1: 5.76351	valid_0's rmse: 7.25302
[275]	valid_0's l1: 5.76444	valid_0's rmse: 7.24574
[276]	valid_0's l1: 5.76765	valid_0's rmse: 7.2503
[277]	valid_0's l1: 5.76327	valid_0's rmse: 7.24287
[278]	valid_0's l1: 5.76066	valid_0's rmse: 7.24281
[279]	valid_0's l1: 5.76275	valid_0's rmse: 7.24279
[280]	valid_0's l1: 5.77499	valid_0's rmse: 7.25681
[281]	valid_0's l1: 5.77902	valid_0's rmse: 7.26545
[282]	valid_0's l1: 5.7787	valid_0's rmse: 7.26809
[283]	valid_0's l1: 5.77209	valid_0's rmse: 7.25789
[284]	valid_0's l1: 5.7768	valid_0's rmse: 7.25747
[285]	valid_0's l1: 5.78583	valid_0's rmse: 7.26356
[286]	valid_0's

LGBMRegressor(bagging_fraction=0.9, bagging_freq=2, bagging_seed=3,
              boosting='gbdt', boosting_type='gbdt', class_weight=None,
              colsample_bytree=1.0, early_stopping_round=2000,
              feature_fraction=0.99, feature_fraction_seed=2,
              importance_type='split', learning_rate=0.1, max_bin=500,
              max_depth=10, metric='l2_root', min_child_samples=20,
              min_child_weight=0.001, min_data_in_leaf=15, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_iterations=10000, num_leaves=31,
              objective='regression', random_state=None, reg_alpha=0.0,
              reg_lambda=0.0, silent=True, subsample=1.0,
              subsample_for_bin=200000, ...)

In [ ]:
pred1 = gbm.predict(X_test, num_iteration = gbm.best_iteration_) 
pred2 = gbm.predict(X_train, num_iteration = gbm.best_iteration_) 
rmse = np.sqrt(MSE(y_test, pred1)) 
rmse1 = np.sqrt(MSE(y_train, pred2)) 
print("RMSE : % f" %(rmse)) 
print("RMSE : % f" %(rmse1)) 
print(r2_score(y_test,pred1)*100)
print(r2_score(y_train,pred2)*100)

RMSE :  6.676674
RMSE :  5.225198
75.09862931400133
88.52922840117452


In [ ]:
RMSE :  6.676674
RMSE :  5.225198
75.09862931400133
88.52922840117452

88.52922840117452

#Fit

In [ ]:
df = pd.read_csv("/content/exam_mark_prediction_ai_challenge-dataset/test.csv")

In [ ]:
df.shape

(300, 8)

In [ ]:
df = df.drop(['Unnamed: 0'],1)
df.head(2)

gender ethnicity  ... reading score writing score
0  female   group C  ...            67            72
1    male   group E  ...            60            59

[2 rows x 7 columns]

In [ ]:
med_price_per_mat_dict = df.groupby('ethnicity')['writing score'].mean().to_dict()
df['med_price_per_mat'] = df['ethnicity'].map(med_price_per_mat_dict )

In [ ]:
df_text = df[['gender','ethnicity','parental level of education','lunch']]

In [ ]:
df_num = df[['reading score','writing score']]

In [ ]:

df_num.head(2)

reading score  writing score
0             67             72
1             60             59

In [ ]:
df_text['main'] = df_text[df_text.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1)

df_text.main.head(3)

0         female,group C,some college,standard
1           male,group E,some college,standard
2    female,group C,bachelor's degree,standard
Name: main, dtype: object

In [ ]:
X_text = df_text.main

In [ ]:
import regex as re
model = []
for i in range(0, df.shape[0]):
    data = re.sub(r'\W', ' ', str(X_text[i]))
    data = data.lower()
    data = re.sub(r'^br$', ' ', data)
    data = re.sub(r'\s+br\s+',' ',data)
    data = re.sub(r'\s+[a-z]\s+', ' ',data)
    data = re.sub(r'^b\s+', '', data)
    data = re.sub(r'\s+', ' ', data)
    model.append(data)   

In [ ]:
model[0]

'female group some college standard'

In [ ]:
#vector = TfidfVectorizer(max_features = 20, min_df = 1, max_df = 0.99, stop_words = stopwords.words('english'))
X_text = vector.transform(model).toarray()

In [ ]:
df_num.shape

(300, 2)

In [ ]:
df_num = scaler.transform(df_num)
df_num

array([[ 0.57142857,  0.67058824],
       [ 0.48051948,  0.51764706],
       [ 0.90909091,  0.94117647],
       [ 0.32467532,  0.36470588],
       [ 0.68831169,  0.76470588],
       [ 0.96103896,  0.95294118],
       [ 0.4025974 ,  0.56470588],
       [ 0.67532468,  0.77647059],
       [ 0.77922078,  0.75294118],
       [ 0.63636364,  0.76470588],
       [ 0.71428571,  0.70588235],
       [ 0.61038961,  0.6       ],
       [ 0.68831169,  0.62352941],
       [ 0.87012987,  0.90588235],
       [ 0.44155844,  0.48235294],
       [ 0.4025974 ,  0.48235294],
       [ 0.51948052,  0.56470588],
       [ 0.8961039 ,  0.81176471],
       [ 0.45454545,  0.57647059],
       [ 0.45454545,  0.58823529],
       [ 0.72727273,  0.78823529],
       [ 0.7012987 ,  0.69411765],
       [ 0.74025974,  0.70588235],
       [ 0.80519481,  0.76470588],
       [ 0.37662338,  0.4       ],
       [ 0.46753247,  0.41176471],
       [ 0.20779221,  0.21176471],
       [ 0.41558442,  0.42352941],
       [ 0.57142857,

In [ ]:
X_num = df_num

In [ ]:
X = np.concatenate((X_text,X_num),axis = 1)
X

array([[0.        , 0.        , 0.75408855, ..., 0.65677276, 0.57142857,
        0.67058824],
       [0.        , 0.        , 0.        , ..., 0.63521651, 0.48051948,
        0.51764706],
       [0.        , 0.67228583, 0.55824548, ..., 0.48620341, 0.90909091,
        0.94117647],
       ...,
       [0.        , 0.        , 0.46383649, ..., 0.40397799, 0.45454545,
        0.57647059],
       [0.        , 0.67228583, 0.55824548, ..., 0.48620341, 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.39880435, 0.5974026 ,
        0.62352941]])

In [ ]:
pred = reg.predict(X)
pred

array([-6.77468538e+12, -6.55233022e+12, -5.01524321e+12, -4.92299794e+12,
       -5.01524321e+12, -5.01524321e+12, -4.92299794e+12, -5.01524321e+12,
       -6.55233022e+12, -4.16707864e+12, -6.55233022e+12, -5.01524321e+12,
       -3.40123453e+12, -4.92299794e+12, -3.40123453e+12, -4.92299794e+12,
       -4.92299794e+12, -3.40123453e+12, -6.77468538e+12, -5.01524321e+12,
       -6.77468538e+12, -4.11371203e+12, -4.16707864e+12, -4.16707864e+12,
       -3.37202881e+12, -3.40123453e+12, -4.44369785e+12, -4.16707864e+12,
       -3.81771131e+12, -3.40123453e+12, -4.92299794e+12, -3.81771131e+12,
       -4.11371203e+12, -4.16707864e+12, -5.01524321e+12, -4.16707864e+12,
       -5.01524321e+12, -4.16707864e+12, -6.77468538e+12, -4.11371203e+12,
       -4.16707864e+12, -3.81771131e+12, -5.01524321e+12, -3.81771131e+12,
       -4.92299794e+12, -4.92299794e+12, -6.77468538e+12, -4.11371203e+12,
       -6.55233022e+12, -4.11371203e+12, -5.01524321e+12, -4.16707864e+12,
       -6.55233022e+12, -

In [ ]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import KFold,StratifiedKFold
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_log_error

errlgb = []
y_pred_totlgb = []

fold = KFold(n_splits = 10, shuffle=True, random_state=42)

for train_index, test_index in fold.split(X1):
    X_train, X_test = X1.loc[train_index], X1.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]

    lgbm = RandomForestRegressor()
    lgbm.fit(X_train, y_train)

    y_pred_lgbm = lgbm.predict(X_test)
    print("RMSE LGBM: ",  np.sqrt(MSE(y_test, y_pred_lgbm)))
    print("R2 LGBM: ",  r2_score(y_test,y_pred_lgbm)*100)
    print("**********************")
    errlgb.append(np.sqrt(MSE(y_test, y_pred_lgbm)))
    p = lgbm.predict(X)
    y_pred_totlgb.append(p)

RMSE LGBM:  6.717143198178914
R2 LGBM:  74.79584645387459
**********************
RMSE LGBM:  6.530665952484831
R2 LGBM:  83.73446346717336
**********************
RMSE LGBM:  6.852763848426529
R2 LGBM:  86.88320565112161
**********************
RMSE LGBM:  5.212114004575948
R2 LGBM:  86.44189178860404
**********************
RMSE LGBM:  6.314157002509555
R2 LGBM:  79.27259118064933
**********************
RMSE LGBM:  6.032364639631209
R2 LGBM:  79.13355278421274
**********************
RMSE LGBM:  5.651632036903638
R2 LGBM:  87.35553741903067
**********************
RMSE LGBM:  5.999190806212858
R2 LGBM:  85.58557460629098
**********************
RMSE LGBM:  5.595024867920011
R2 LGBM:  88.49921079038013
**********************
RMSE LGBM:  6.63257564069275
R2 LGBM:  72.51189877520427
**********************


In [ ]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import KFold
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_log_error

errlgb = []
y_pred_totlgb = []

fold = KFold(n_splits = 10, shuffle=True, random_state=42)

for train_index, test_index in fold.split(X1):
    X_train, X_test = X1.loc[train_index], X1.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]

    lgbm = LGBMRegressor(**param)
    lgbm.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=0, early_stopping_rounds=200)

    y_pred_lgbm = lgbm.predict(X_test)
    print("RMSE LGBM: ",  np.sqrt(MSE(y_test, y_pred_lgbm)))
    print("R2 LGBM: ",  r2_score(y_test,y_pred_lgbm)*100)
    print("**********************")
    errlgb.append(np.sqrt(MSE(y_test, y_pred_lgbm)))
    p = lgbm.predict(X)
    y_pred_totlgb.append(p)

RMSE LGBM:  6.362628523169239
R2 LGBM:  77.38607022581802
**********************
RMSE LGBM:  6.187023168532432
R2 LGBM:  85.40120741558631
**********************
RMSE LGBM:  6.3254420873334585
R2 LGBM:  88.82421738777607
**********************
RMSE LGBM:  5.147226816158198
R2 LGBM:  86.77736848747892
**********************
RMSE LGBM:  5.965370179051521
R2 LGBM:  81.49926178027671
**********************
RMSE LGBM:  5.7070893322269365
R2 LGBM:  81.32319084428697
**********************
RMSE LGBM:  5.362433998068731
R2 LGBM:  88.6164809513926
**********************
RMSE LGBM:  6.109917963681588
R2 LGBM:  85.04856962294123
**********************
RMSE LGBM:  5.454390334269311
R2 LGBM:  89.07010399289554
**********************
RMSE LGBM:  5.803599797628058
R2 LGBM:  78.95372542094425
**********************


In [ ]:
np.mean(errlgb,0)

6.153763199753625

In [ ]:
lgbm_final = np.mean(y_pred_totlgb,0)

In [ ]:
df_sub = pd.DataFrame(data = pred , columns= ['math score'])

In [ ]:
df_sub

math score
0     63.540000
1     62.590000
2     85.840000
3     48.850000
4     67.380000
..          ...
295   71.420000
296   48.310000
297   58.783333
298   96.867810
299   72.256667

[300 rows x 1 columns]

In [ ]:
df_sub.to_csv('result_math.csv',index_label=['idx'])